### ISSUE TITLE
geoip2 is broken

### ISSUE THREAD

**Issue by ajholland** [zmap/zannotate#17]
I attempted to run zannotate with geoip2, got the following:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 11 [running]:
github.com/zmap/zannotate.AnnotateWorker(0x6bf2a0, 0xc42000c4e0, 0xc42007c180, 0xc42007c1e0, 0x5d8445, 0x9, 0xc420014530, 0x2)
	/home/ahollan/go/src/github.com/zmap/zannotate/annotate.go:166 +0x664
created by github.com/zmap/zannotate.DoAnnotation
	/home/ahollan/go/src/github.com/zmap/zannotate/annotate.go:209 +0x49b
panic: interface conversion: interface {} is nil, not map[string]interface {}
```

Looks like it was using the default json annotation field which is `zannotate`. I was able to get zannotate to run by sending `--json-annotation-field= `. Output didn't include ip addresses that I provided. I reverted to `c75f40d125c378597d329011ecc5ee2b7da1d24c` and then called it a night.

It also looks like csv is no longer supported.

**Comment by zakird** [comment]
This is fixed by that last commit to master.
